name: "Release"

on:
  push:
    tags: # run when release has been tagged, however ignore non-official semver tags (release candidates, etc)
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "!v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: write

jobs:
  build-test:
    name: "Build & test"

    uses: ./.github/workflows/build-test.yaml

  release:
    name: "Release"

    needs: build-test

    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v5

    - name: Download binaries
      uses: actions/download-artifact@v5
      with:
        path: dist

    - name: "Release"
      uses: softprops/action-gh-release@v2
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          LICENSE
          dist/*/*
